name: Secure Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  secure-scan:
    name: Build and Scan Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Build with Maven and generate dependencies
        run: mvn clean package -DskipTests

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan Maven Dependencies with Grype
        run: grype dir:. -o json > grype-maven-report.json

      - name: Upload Grype Maven report
        uses: actions/upload-artifact@v4
        with:
          name: grype-maven-report
          path: grype-maven-report.json

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - name: Scan Maven Dependencies with Trivy
        run: trivy fs --scanners vuln --format json --output trivy-maven-report.json .

      - name: Upload Trivy Maven report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-maven-report
          path: trivy-maven-report.json

      - name: Build local Docker image
        run: docker build -t cicd-app:local .

      - name: Run Grype scan on Docker Image
        run: grype cicd-app:local --scope all-layers -o json > grype-docker-report.json

      - name: Upload Grype Docker report
        uses: actions/upload-artifact@v4
        with:
          name: grype-docker-report
          path: grype-docker-report.json

      - name: Run Trivy scan on Docker Image
        run: trivy image cicd-app:local --scanners vuln --format json --output trivy-docker-report.json

      - name: Upload Trivy Docker report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-docker-report
          path: trivy-docker-report.json
